### ISSUE TITLE
current tag link is relative to the route not the url provided?

### ISSUE THREAD

**Issue by thanikkal** [lassebunk/gretel#61]
Thank you for this excellent gem.
I think i am running into an issue with the :link_current option though.
(on Rails 4.2.4 and Gretel version gretel-3.0.8)

while trying to provide a different link to the current tag like so:

```ruby
crumb :employees do
  link "Employees ", employees_path
end

crumb :employee do | employee |
  link "#{employee.name} (#{employee.code})", "/go/here"
  parent :employees
end
```
View:
/employees/edit.html.erb
```ruby
<% breadcrumb :employee, @employee%>
```
the link here is rendered as  **/employees/[ID]/edit**

/employees/show.html.erb
```ruby
<% breadcrumb :employee, @employee %>
```
the link here is rendered as **/employees/[ID]**

it doesn't link to **"/go/here"** link that I provide.
Isn't this behavior incorrect?

Thanks.

**Comment by WilHall** [comment]
Hi @thanikkal; yes, this behavior is intentional.

The last breadcrumb is, by definition, a breadcrumb for the current page. Thus, it always links to the current page. It would be an odd user experience for it *not* to link to the current page.

Also by default, the last breadcrumb is not linked to - you would have had to set the `:link_current` option to `true`.

If you *really* need to get around this and change the last breadcrumb's URL, you can do something like the following when you render the breadcrumbs:

```
breadcrumbs(:link_current => true).tap do |crumbs|
  crumbs.last.url = "/foo/bar";
  crumbs
end
```

I realize this workaround is far from ideal. I'm going to give some thought to whether or not there should be a way to change the behavior of `:link_current`.

**Comment by WilHall** [comment]
Closing this issue in favor of #28.
